name: Deploy

on:
  push:
    branches:
      - main
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Check free-tier compliance
        run: |
          echo "Checking free-tier compliance..."
          # Add your free-tier compliance check logic here
          # For example, check if any changes might exceed free limits

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to production..."
          npx vercel --prod --env-file .env.production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to QA
        if: github.ref == 'refs/heads/qa'
        run: |
          echo "Deploying to QA environment..."
          npx vercel --env-file .env.qa
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 